apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calculator-api
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: calculator.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: calculator-api
                port:
                  number: 80
  tls:
    - hosts:
        - calculator.example.com
      secretName: calculator-prod-tls
